export { default as Home } from './Home.tsx'
export { default as Leads } from './Leads.tsx'
export { default as Login } from './Login.tsx'
export { default as Profile } from './Profile.tsx'
export { default as Registration } from './Registration.tsx'
